twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
    globals:
        locales: '%app_locales%'
