monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            max_files: 10
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        file_log:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.APP.log"
            level: debug
            channels: ["app"]
            max_files: 10
        firephp:
            type: firephp
            level: debug
        chromephp:
            type: chromephp
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
